---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
name: samsonite-os
description: Custom Bazzite GNOME/NVIDIA DX Image
base-image: ghcr.io/ublue-os/bazzite-gnome-nvidia
image-version: latest

modules:
  - type: files
    files:
      - source: system
        destination: /

  # Install RPM Packages
  - type: rpm-ostree
    install:
      # --- Core DX Layer (Bluefin DX) ---
      # Containers
      - incus
      - incus-agent
      - lxc
      - podman-compose
      - podman-tui
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
      
      # Development Tools
      - code
      - android-tools
      - iotop
      - sysprof
      - trace-cmd
      - bpftop
      - bpftrace

      # Admin/Web
      - cockpit-bridge
      - cockpit-machines
      - cockpit-podman

      # --- Bazzite DX Extras ---
      - ccache
      - restic
      - rclone
      - zsh
      - python3-ramalama

  # Enable Services
  - type: systemd
    system:
      enabled:
        - docker.socket
        - podman.socket
        - libvirtd.service
        - bluefin-dx-groups.service
        - incus-workaround.service

  # Install Flatpaks
  - type: default-flatpaks
    notify: true
    system:
      repo-url: https://dl.flathub.org/repo/flathub.flatpakrepo
      repo-name: flathub
      repo-title: Flathub
      install:
        # Core DX
        - io.podman_desktop.PodmanDesktop
        - org.gnome.dspy
        - app.drey.Warp
        - io.github.flattool.Warehouse
        # Creativity / Productivity (Curated)
        - org.blender.Blender
        - org.gimp.GIMP
        - org.kde.kdenlive
        - com.obsproject.Studio

  - type: signing